[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
onchainvoting = "CraCBFcQKxRU4d72HFPRNZbTQJQnanaeBxPRfyxB78am"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/solanauser/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
