[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
selfcustodialfacebook = "EFEL7YPBM7r8VVtmNre8Qs2sXAAfusDMSarspGcqeJG5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/solanauser/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
