[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
noncustodialescrow = "3TBDysJ2uQ7F8JbLAymFKcjwzjzZ3d8acWRcjYUUpURt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/solanauser/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
